/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_ii_xtraplatform_cli_Cli */

#ifndef _Included_de_ii_xtraplatform_cli_Cli
#define _Included_de_ii_xtraplatform_cli_Cli
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_ii_xtraplatform_cli_Cli
 * Method:    execute
 * Signature: (Lde/ii/xtraplatform/cli/CommandHandler;)V
 */
JNIEXPORT void JNICALL Java_de_ii_xtraplatform_cli_Cli_execute
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
