name: xtractl

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/ldproxy/golang-jdk:1.2
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_ro_token }}
    steps:
      - name: clone
        uses: actions/checkout@v4
      - name: build
        working-directory: ./xtractl
        env:
          CI_COMMIT_BRANCH: ${{ github.ref_name }}
          CI_COMMIT_SHA: ${{ github.sha }}
          CI_COMMIT_TAG: ${{ github.ref_type == 'tag' && github.ref_name || '' }}
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o dist/linux-amd64/xtractl -ldflags="-s -w -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitTag=${CI_COMMIT_TAG} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitSha=${CI_COMMIT_SHA} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitBranch=${CI_COMMIT_BRANCH}"
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -o dist/linux-arm64/xtractl -ldflags="-s -w -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitTag=${CI_COMMIT_TAG} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitSha=${CI_COMMIT_SHA} -X github.com/interactive-instruments/xtraplatform-cli/xtractl/cmd.gitBranch=${CI_COMMIT_BRANCH}"
          cp Dockerfile dist/
      - name: log1
        run: |
          ls -lR ./xtractl/dist
      - name: upx
        uses: docker://backplane/upx:latest
        with:
          args: upx --best xtractl/dist/linux-amd64/xtractl xtractl/dist/linux-arm64/xtractl
      - name: log2
        run: |
          ls -lR ./xtractl/dist
      - name: save
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./xtractl/dist
          retention-days: 1

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: load
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: log1
        run: |
          ls -lR
      - uses: bhowell2/github-substring-action@1.0.2
        id: short-sha
        with:
          value: ${{ github.sha }}
          length_from_start: 7
      - uses: bhowell2/github-substring-action@1.0.2
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        id: short-tag
        with:
          value: ${{ github.ref_name }}
          index_of_str: "v"
      - name: login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ghcr_rw_token }}
      - name: buildx
        uses: docker/setup-buildx-action@v3
      - name: push
        if: ${{ github.ref_type == 'branch' && github.ref_name == 'main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          pull: true
          tags: |
            ghcr.io/ldproxy/xtractl:next
            ghcr.io/ldproxy/xtractl:next-${{steps.short-sha.outputs.substring}}
          platforms: |
            linux/amd64
            linux/arm64
      - name: push-branch
        if: ${{ github.ref_type == 'branch' && github.ref_name != 'main' }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          pull: true
          tags: |
            ghcr.io/ldproxy/xtractl:${{ github.ref_name }}
            ghcr.io/ldproxy/xtractl:${{ github.ref_name }}-${{steps.short-sha.outputs.substring}}
          platforms: |
            linux/amd64
            linux/arm64
      - name: tag
        if: ${{ github.ref_type == 'tag' && startsWith(github.ref_name, 'v') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          pull: true
          tags: |
            ghcr.io/ldproxy/xtractl:${{ steps.short-tag.outputs.substring }}
            ghcr.io/ldproxy/xtractl:latest
          platforms: |
            linux/amd64
            linux/arm64
